import json
from datetime import datetime, date, timezone

all_candidates = []
macro_summary = {}
rotation_summary = {}
etf_flow_dict = {}

CORE_STOCKS = ['TSM','NVDA','ANET','VRT','MU','AVGO','PLTR','VST','CEG','ORCL','AMZN','META','MSFT']

macro_summary = {
    'market_regime': 'BULL_DETERIORATING',
    'vix': 22.5,
    'treasury_10yr': 4.71,
    'dxy': 104.0,
    'copper_trend': 'NEUTRAL',
    'spy_5d_return': -0.019,
    'spy_20d_return': 0.022,
    'macro_themes': [
        'Fed holds at 3.50-3.75% (4th consecutive hold); markets pricing in rate HIKE by Oct 2026 under new chair Warsh — hawkish pivot changes the risk premium calculus for every growth name',
        '10yr Treasury at 4.71% — highest since Jan 2025; Middle East tensions + Brent crude near $100 driving yields; rising yield curve is a direct DCF headwind for high-multiple tech/AI names',
        'New Trump tariffs took effect July 24 across multiple sectors; trade uncertainty is adding a risk-premium to any name with cross-border supply chains (TSMC ADR, NVDA China revenue)',
        'July 2026 AI hardware selloff: SOX index -15%+ in July, worst month since 2008; Mag7 shed ~$800B in market cap on July 23 alone; this is a VALUATION RESET, not a fundamental breakdown — AI capex from hyperscalers continues unabated',
        'Hyperscaler AI capex arms race: combined spend projected to exceed $700B in 2026; Q2 earnings focus is shifting from spend levels to ROI proof points; META reports July 29, AMZN July 30',
    ],
    'emerging_tech_themes': [
        'NVDA GB300 Blackwell Ultra demand "off the charts" per Jensen Huang; $500B in purchase commitments outstanding; supply constrained through end-2026; $65B Q4 FY2026 guidance',
        'TSMC CoWoS advanced packaging SOLD OUT through 2026-2027; N2 ramping at 70% CAGR through 2028; $265B Arizona gigafab investment; packaging is the binding constraint for all AI chip production',
        'Micron HBM4 in high-volume production for NVDA Vera Rubin — ramping 2x faster than HBM3E; 2026 allocations fully contracted; attention now shifts to 2027 supply visibility vs SK Hynix',
        'AVGO custom silicon AI revenue $10.8B in Q2 (+143% YoY); 6 hyperscaler customers (Google, Meta, OpenAI, Anthropic, Amazon, Apple rumored); CEO targeting $100B AI rev for FY2027',
        'Training-to-inference shift accelerating: NVDA wins training; AVGO/MRVL custom ASICs preferred for inference at hyperscaler scale — margin differentiation long-term',
        'Liquid cooling is now mandatory for Blackwell (>1000W TDP); Vertiv is the dominant commercial provider with $15B backlog and 30% organic growth guidance for 2026',
        'Nuclear power is the only scalable 24/7 carbon-free AI data center power source; CEG and VST have locked up multi-GW capacity in 20-year PPAs with Meta, Microsoft — these are annuity streams',
        'INTC turnaround validated: Q2 2026 revenue $16.1B (+25% YoY, best in 15 years), Data Center +59%; Intel Foundry +31% — CHIPS Act funding + Gaudi AI ramp creating a second foundry option',
    ],
    'taiwan_signals': [
        'TSMC CoWoS sold out; packaging capacity growing >80% CAGR — the single biggest bottleneck constraining AI chip supply globally',
        'TSMC N2 (2nm) in volume production 2026; Arizona fab Fab 21 Phase 2 (3nm) on track for 2027; sole-source sub-3nm foundry through at least 2028',
        'Cross-strait risk LOW-MEDIUM: Polymarket only 13% probability of PRC invasion before end 2026; US intelligence says attack unlikely near-term; remains a tail risk to price in (~5-10% discount on TSM ADR)',
        'DXY at ~104 creates persistent earnings translation headwind for TSM ADR holders — every 1pt DXY rise = ~1.5% TSM ADR headwind at current revenue mix',
        'Taiwan ODMs (Quanta, Wiwynn) running full AI server capacity; US equivalent DELL/HPE benefiting; VRT as cooling supplier to all major server ODMs',
    ],
    'govt_catalysts': [
        {'company': 'INTC', 'type': 'CHIPS Act', 'amount': '$7.86B', 'status': 'FINALIZED', 'priced_in': 'YES', 'upside': 'Disbursements through 2028 as milestones hit; Foundry customer wins provide incremental upside', 'risk': 'Execution risk on 18A node yield ramp'},
        {'company': 'TSMC', 'type': 'CHIPS Act + AZ Investment', 'amount': '$15B+ (portion of $39B pool)', 'status': 'ONGOING', 'priced_in': 'PARTIALLY', 'upside': 'AZ CoWoS packaging facility announced Jan 2026; reduces geopolitical risk discount on TSM ADR', 'risk': 'Cost overruns, talent constraints in Arizona'},
        {'company': 'PLTR', 'type': 'DoD AI/Maven Contract', 'amount': 'Up to $10B 10-year Army enterprise', 'status': 'CONFIRMED', 'priced_in': 'PARTIALLY', 'upside': 'Maven expansion to classified networks + 7 more agencies; DoD committed $32B in H1 FY2026 to AI contracts', 'risk': 'Active DIA contract dispute with Pentagon; congressional oversight risk'},
        {'company': 'MSFT/AMZN/NVDA/ORCL', 'type': 'DoD AI Classified', 'amount': '$32B+ H1 FY2026', 'status': 'CONFIRMED', 'priced_in': 'PARTIALLY', 'upside': 'Recurring high-margin gov revenue; classified work is less price-sensitive and stickier than commercial', 'risk': 'Political risk of DoD AI expansion; congressional scrutiny'},
        {'company': 'CEG', 'type': 'DOE Nuclear + SMR Licensing', 'amount': 'Multiple DOE programs TBD', 'status': 'PENDING', 'priced_in': 'NO', 'upside': 'Three Mile Island restart is the template; additional nuclear restarts + SMR licensing = long-term capacity expansion', 'risk': 'NRC approval delays, cost overruns, political opposition'},
        {'company': 'MU', 'type': 'CHIPS Act HBM Expansion', 'amount': 'Portion of $39B pool', 'status': 'ALLOCATED', 'priced_in': 'YES', 'upside': 'Domestic HBM4 production moat; reduces SK Hynix/Samsung import dependency for US AI supply chain', 'risk': 'Samsung HBM4 re-qualification would end MU pricing power'},
    ],
    'cross_strait_risk': 'LOW_MEDIUM',
}

rotation_summary = {
    'sector_rotation_today': 'AI_HARDWARE -> CLOUD_SOFTWARE + AI_POWER + INDUSTRIALS',
    'rotation_favored': ['META', 'AMZN', 'MSFT', 'PLTR', 'NOW', 'CEG', 'VST', 'VRT', 'PWR', 'ETN', 'INTC'],
    'rotation_disfavored': ['NVDA', 'TSM', 'MU', 'AMD', 'AMAT', 'LRCX'],
    'rotation_rationale': 'July 2026: valuation-driven rotation OUT of AI hardware semis (SOX -15%, worst month since 2008) after a 130% rally; rising yields (4.71%) + Fed hike pricing compress growth multiples. Institutional money rotating INTO cloud software earnings plays (META/AMZN reporting July 29-30) and defensive AI power (CEG/VST 20-year nuclear PPAs). This is a multiple compression event, not an earnings revision event — own the thesis, not the crowded trade.',
}

etf_flow_dict = {
    'SOXX': 'INFLOW_ON_DIPS',
    'SMH': 'INFLOW_ON_DIPS',
    'IGV': 'NEUTRAL',
    'XLK': 'OUTFLOW',
    'XLY': 'NEUTRAL',
    'XLF': 'INFLOW',
    'XLV': 'NEUTRAL',
    'XLE': 'INFLOW',
    'XLI': 'INFLOW',
    'XLC': 'NEUTRAL',
    'XLRE': 'OUTFLOW',
    'XLU': 'NEUTRAL',
    'XLP': 'INFLOW',
    'ARKK': 'OUTFLOW',
}

# ── CANDIDATES ────────────────────────────────────────────────────────────────
raw = [
  {
    'symbol': 'AVGO', 'company': 'Broadcom Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 67, 'close': 248.0,
    'rs_vs_spy_20d': 0.052, 'pct_from_52w_high': -0.04, 'volume_ratio': 1.35,
    'ai_category': 'Chips/Custom Silicon',
    'valuation': {'forwardPE': 31, 'peg': 1.3, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider buys; institutional ownership very high; Druckenmiller added new position Q1 2026',
    'short_interest_pct': 0.015, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-09-03', 'earnings_days_away': 41, 'earnings_risk': 'LOW',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Large call sweeps at $250-$270 strikes, 60d expiry',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Multiple PTs raised post Q2; consensus ~$275; Citi raised to $290 citing FY2027 $100B AI revenue path',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'HIGH',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': 'Custom silicon duopoly with MRVL; 6 hyperscaler XPU customers; AI chip revenue $10.8B Q2 (+143% YoY); CEO guiding $100B FY2027; switching cost from XPU to GPU is architectural — not a procurement decision',
    'smart_money_13f': 'SMART_MONEY_ACCUMULATING',
    'smart_money_detail': 'Druckenmiller new position Q1 2026; Situational Awareness LP long; 13F universe net buyer',
    'sector_rotation_impact': 'NEUTRAL',
    'buy_zone': '$225-$250',
    'price_target': '$310',
    'stop_loss': '$195',
    'thesis_hold_conditions': 'Hold as long as: hyperscaler XPU TAM growing; AVGO retains 5+ XPU design wins; AI chip revenue growth stays >100% YoY; gross margins above 68%',
    'thesis_break_triggers': 'EXIT if: 2+ hyperscalers cancel XPU programs and revert to NVDA GPU-only OR AI chip revenue growth decelerates below 50% YoY for 2 consecutive quarters OR custom silicon commoditizes via open-source XPU designs',
    'key_catalysts': 'FY2027 $100B AI revenue guide, Q3 earnings Sept, 6th hyperscaler XPU design win announcement',
    'key_risks': 'NVDA opens CUDA to non-NVDA chips (moat erosion), hyperscaler capex cuts, valuation multiple compression in rising-rate environment',
    'analyst_note': 'AVGO is the single best-positioned AI chip play for investors who want NVDA exposure without the NVDA-specific risks. The custom silicon story is structurally different: each XPU design win is a 5-7 year locked-in revenue stream because the software stack is co-developed with the hyperscaler. With 6 customers and $100B FY2027 AI revenue in management guidance, this is the highest-conviction semiconductor name for the 12-24 month horizon — and the sector rotation headwinds that are crushing NVDA/MU apply less here because AVGO is classified as technology infrastructure, not AI hardware per se. Druckenmiller adding new position in Q1 2026 is a high-quality signal.',
  },
  {
    'symbol': 'AMZN', 'company': 'Amazon.com Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 68, 'close': 212.0,
    'rs_vs_spy_20d': 0.028, 'pct_from_52w_high': -0.06, 'volume_ratio': 1.4,
    'ai_category': 'Cloud/AI Infrastructure',
    'valuation': {'forwardPE': 35, 'peg': 1.6, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'Berkshire sold out of AMZN in Q1 2026 (Buffett trimming tech); Bridgewater added; mixed signals — not a red flag given Berkshire tax optimization rationale',
    'short_interest_pct': 0.008, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-30', 'earnings_days_away': 6, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'High options volume ahead of July 30 earnings; call/put ratio elevated bullish',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'BofA raised AWS growth forecast to 33% YoY; consensus Strong Buy; avg PT implies 29% upside',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': 'AWS #1 cloud at ~32% market share; Trainium silicon = in-house inference chip reducing NVDA dependency and boosting margins; Bedrock AI platform + Anthropic partnership; AWS margins expanding as AI demand accelerates',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Berkshire sold Q1 2026; Bridgewater adding; net mixed but neither is a structural exit signal',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$195-$215',
    'price_target': '$265',
    'stop_loss': '$175',
    'thesis_hold_conditions': 'Hold as long as: AWS revenue growth stays above 28% YoY; AI/Bedrock attach rate growing; retail operating margins expand; Trainium ramp reducing NVDA spend',
    'thesis_break_triggers': 'EXIT if: AWS growth decelerates below 20% for 2+ consecutive quarters OR Azure/GCP take meaningful AWS share (>3pp in 12 months) OR Bedrock/Anthropic partnership unwinds',
    'key_catalysts': 'Q2 earnings July 30 (consensus $196.7B rev, $1.82 EPS), AWS 33% growth print, Trainium chip ramp update, Bedrock enterprise customer count',
    'key_risks': 'Q2 earnings miss (stocks at ALL-TIME HIGH expectations), rising capex weighing on FCF, Berkshire exit creates technical overhang',
    'analyst_note': 'AMZN is a MUST-OWN into July 30 earnings — this is one of two stocks (with META) that the current rotation explicitly favors. AWS guided above 33% growth, BofA raised its growth forecast, and management indicated Q2 operating income of $20-24B. The Trainium chip story is underappreciated: every Trainium chip deployed reduces NVDA spend and expands AWS margins. The 6-day event risk is real but with consensus at $196.7B revenue and the setup this clean, the risk/reward is asymmetric to the upside. Buy the dip if it opens down.',
  },
  {
    'symbol': 'INTC', 'company': 'Intel Corporation', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 72, 'close': 58.5,
    'rs_vs_spy_20d': 0.065, 'pct_from_52w_high': -0.03, 'volume_ratio': 2.8,
    'ai_category': 'Chips/Foundry Turnaround',
    'valuation': {'forwardPE': 28, 'peg': 1.1, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider buys/sells recently; Druckenmiller added INTC in Q1 2026 — highest-quality external signal available',
    'short_interest_pct': 0.065, 'squeeze_risk': 'HIGH',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-23', 'earnings_days_away': 1, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Unusual call activity July 23-24; $60+ strikes; squeeze setup with 6.5% short interest',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Q2 beat by $0.20 EPS; DC+AI revenue +59% YoY; Foundry +31%; Q3 guide above consensus; multiple analysts raising PTs today',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'COMPETITIVE',
    'pricing_power_detail': 'Intel Foundry still behind TSMC (N2) but 18A node ramping; CHIPS Act $7.86B enables capacity without market pricing power yet; Gaudi AI accelerator gaining traction in inference workloads',
    'smart_money_13f': 'SMART_MONEY_ACCUMULATING',
    'smart_money_detail': 'Druckenmiller new INTC position Q1 2026; turnaround thesis gaining traction among value-oriented HFs',
    'sector_rotation_impact': 'NEUTRAL',
    'buy_zone': '$54-$60',
    'price_target': '$78',
    'stop_loss': '$46',
    'thesis_hold_conditions': 'Hold as long as: Data Center+AI revenue stays above 50% growth YoY; Intel Foundry 18A yields improving each quarter; CHIPS Act disbursements on schedule; Gaudi market share in inference growing',
    'thesis_break_triggers': 'EXIT if: Intel Foundry loses another major external customer OR 18A yield issues resurface publicly OR Data Center AI revenue growth falls below 30% YoY for 2 consecutive quarters',
    'key_catalysts': 'Q2 just BEAT (revenue $16.1B +25% YoY, best in 15 years, DC+AI +59%); +3.6% premarket July 24; short squeeze potential; Q3 guidance above consensus',
    'key_risks': 'Stock up ~170% YTD — priced for perfection; Foundry still losing money; execution risk on 18A remains; AMD x86 competition',
    'analyst_note': 'INTC just delivered the most important earnings beat of the turnaround: $16.1B revenue, +25% YoY — the best growth rate in 15 years — and DC+AI revenue surged 59%. The market had partially priced this in (stock up 170% YTD) but the magnitude of the beat and the Q3 guide above consensus creates a near-term momentum window. Druckenmiller was early here. The short squeeze setup (6.5% short interest + beat + gap up) is real. For longer-term holders, the thesis is Intel Foundry achieving 18A profitability by 2027 — a second source of advanced chips reduces geopolitical risk premium on TSM. This is not a HOLD — it is a BUY on any weakness in the next 2 weeks.',
  },
  {
    'symbol': 'META', 'company': 'Meta Platforms Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 70, 'close': 710.0,
    'rs_vs_spy_20d': 0.018, 'pct_from_52w_high': -0.05, 'volume_ratio': 1.3,
    'ai_category': 'Cloud/AI Software',
    'valuation': {'forwardPE': 24, 'peg': 1.2, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'CLO Newstead sold 519 shares under 10b5-1 plan — routine, not signal. Zuckerberg on fixed diversification plan.',
    'short_interest_pct': 0.009, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-29', 'earnings_days_away': 5, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Large call sweeps $720-$760 strikes ahead of July 29 earnings; institutional positioning bullish',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Multiple upgrades post Meta Compute launch; consensus $743 12-month target; Morgan Stanley raised to $780',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'NONE',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': '3.3B daily active users across WhatsApp/Instagram/Facebook — unmatched ad network moat; Iris custom silicon (September 2026) reduces NVDA dependency and lowers AI inference cost by 30-40%; Meta Compute launch monetizes AI infrastructure as external revenue',
    'smart_money_13f': 'SMART_MONEY_ACCUMULATING',
    'smart_money_detail': 'Top 13F filers concentrated in META and AI infrastructure in Q1 2026; major HF accumulation visible across filings',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$680-$715',
    'price_target': '$800',
    'stop_loss': '$610',
    'thesis_hold_conditions': 'Hold as long as: DAU growth positive; ad revenue per user expanding; AI inference cost declining (Iris chip); Meta Compute gaining enterprise customers; Llama open-source driving developer ecosystem',
    'thesis_break_triggers': 'EXIT if: Q2 revenue misses by >3% OR ad revenue per user declines YoY for 2+ quarters OR Iris chip delayed beyond Q1 2027 OR antitrust breakup risk escalates materially',
    'key_catalysts': 'Q2 earnings July 29 (~$60B revenue expected, +22% YoY); Iris chip production September 2026; Meta Compute cloud platform expansion; Llama 4 enterprise adoption',
    'key_risks': 'Earnings miss on $125-145B capex narrative; EU regulatory risk; TikTok remains a threat to younger demographics',
    'analyst_note': 'META is the cleanest FAANG into Q2 earnings: expected $60B revenue (+22% YoY), $125-145B capex is OFFENSIVE not defensive (Iris chip September, Meta Compute launched), and the rotation explicitly favors software/cloud over hardware. This is not a trade — it is the highest-quality AI monetization story in the market. Meta has already proven AI ROI via ad targeting: AI-powered Advantage+ drove 32% higher ad conversion rates in Q1. Zuckerberg building Meta Compute as a third platform (alongside ads and hardware) makes this a 3x TAM story. Hold through and beyond the July 29 print.',
  },
  {
    'symbol': 'TSM', 'company': 'Taiwan Semiconductor Mfg. Co.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 52, 'close': 174.0,
    'rs_vs_spy_20d': -0.008, 'pct_from_52w_high': -0.10, 'volume_ratio': 1.1,
    'ai_category': 'Foundry',
    'valuation': {'forwardPE': 22, 'peg': 0.9, 'vs_peers': 'CHEAP'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No US Form 4 equivalents; institutional ownership very high; CC Wei aligned with long-term strategy',
    'short_interest_pct': 0.012, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-10-16', 'earnings_days_away': 84, 'earnings_risk': 'LOW',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal options activity; no unusual positioning',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Consensus strong buy; avg PT ~$225 ADR; CoWoS sold-out narrative driving upgrades',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'EXTREME',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': 'Sole sub-3nm foundry globally; N2 capacity booked 12-18 months ahead; CoWoS packaging has zero competition at scale; every AI chip (NVDA/AMD/AVGO/GOOG TPU/AWS Trainium) runs through TSMC — pricing power is structural and permanent within this decade',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': '13F data shows stable institutional ownership; no major new entries or exits in Q1 2026',
    'sector_rotation_impact': 'DISFAVORED',
    'buy_zone': '$162-$178',
    'price_target': '$230',
    'stop_loss': '$140',
    'thesis_hold_conditions': 'Hold as long as: CoWoS demand from NVDA/AMD/AVGO intact; N2 yield ramping on schedule; Arizona fab milestones on track; cross-strait risk stays LOW-MEDIUM',
    'thesis_break_triggers': 'EXIT if: China military escalation materially increases (Polymarket >25% invasion probability) OR Intel 18A/Samsung 2nm achieve competitive yields with TSMC N2 OR NVDA announces shift away from TSMC (extremely unlikely near-term)',
    'key_catalysts': 'Q3 2026 earnings Oct; CoWoS capacity expansion announcement; N2 yield progress update; Arizona CoWoS facility groundbreaking',
    'key_risks': 'Cross-strait geopolitical risk (LOW but nonzero); DXY headwind (~$104 current); July hardware rotation disfavors; CHIPS Act compliance reporting requirements',
    'analyst_note': 'TSM is the most structurally important company in the AI supply chain — every frontier AI chip on earth runs through TSMC. The selloff is a sector rotation event, not a fundamental deterioration. At a PEG of 0.9, TSM is the only PRICING_LEADER in this watchlist trading at CHEAP valuation. The DXY at 104 is a headwind and the hardware rotation will continue near-term, but at ~10% off 52-week high with CoWoS sold out and N2 ramping, the risk/reward here is compelling for patient capital. Add on weakness, not strength.',
  },
  {
    'symbol': 'MSFT', 'company': 'Microsoft Corporation', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 63, 'close': 455.0,
    'rs_vs_spy_20d': 0.012, 'pct_from_52w_high': -0.07, 'volume_ratio': 1.15,
    'ai_category': 'Cloud/AI Software',
    'valuation': {'forwardPE': 33, 'peg': 1.8, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider buys; executives on diversification plans; Satya Nadella compensation aligned with Azure growth',
    'short_interest_pct': 0.007, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-28', 'earnings_days_away': 4, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal pre-earnings positioning; no unusual sweeps',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Rising amid broad tech selloff on strong earnings expectations; consensus Strong Buy; $530 avg PT',
    'news_sentiment': 'NEUTRAL',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': 'Azure #2 cloud with highest AI attach rate; Copilot monetization just beginning ($30/seat x 400M commercial users = $144B TAM); DoD/intelligence classified cloud = high-margin recurring; Office 365 AI bundling creates pricing power at seat level',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership stable; no concentrated new positions or exits in Q1 2026',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$435-$460',
    'price_target': '$560',
    'stop_loss': '$390',
    'thesis_hold_conditions': 'Hold as long as: Azure revenue growth above 35% YoY; Copilot ARPU increasing; DoD/intelligence contracts renewable and expanding; operating leverage improving despite $190B capex',
    'thesis_break_triggers': 'EXIT if: Azure growth decelerates below 25% for 2 consecutive quarters OR Copilot adoption stalls at <20% of Office 365 base OR OpenAI partnership terminally deteriorates',
    'key_catalysts': 'Q4 FY2026 earnings July 28 (4 days); Azure AI revenue as % of total; Copilot seat count and ARPU; DoD contract expansion',
    'key_risks': '$190B 2026 capex creating FCF headwind; OpenAI dependency risk; EU antitrust; stock rising into earnings creates mis-set expectations',
    'analyst_note': 'MSFT is the most defensive of the hyperscalers with the clearest AI monetization path: Copilot bundled into every Office 365 seat at $30/month is a $144B annual TAM at full penetration. Azure AI is outgrowing raw Azure, and the DoD classified cloud relationships create a recession-resistant revenue floor. The $190B capex is FRIGHTENING investors but it is building Copilot, Azure AI, and the next generation of data centers — invest now, harvest 2027-2028. Q4 earnings July 28 are 4 days away; the risk/reward is favorable.',
  },
  {
    'symbol': 'PLTR', 'company': 'Palantir Technologies Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 73, 'close': 142.0,
    'rs_vs_spy_20d': 0.041, 'pct_from_52w_high': -0.04, 'volume_ratio': 1.6,
    'ai_category': 'AI Software/Defense',
    'valuation': {'forwardPE': 150, 'peg': 2.0, 'vs_peers': 'EXPENSIVE'},
    'insider_activity': 'BEARISH',
    'insider_detail': 'Net $15.6B insider selling across NVDA/PLTR/META over 3-year trailing period; Karp and insiders on continuous diversification plans — not actionable as near-term bearish signal at these growth rates',
    'short_interest_pct': 0.05, 'squeeze_risk': 'HIGH',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-04', 'earnings_days_away': 11, 'earnings_risk': 'EARNINGS_NEAR',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'High call volume at $145-$160 strikes, 30-45d expiry; retail + institutional accumulation',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Loop Capital $220 PT Buy; avg consensus $192.76; Q1 US revenue +104% YoY the key driver',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Maven AI is embedded in DoD kill-chain decision systems — switching cost is operational risk of military mission failure; $10B 10-year Army enterprise agreement; 7+ additional agency expansions ongoing; AIP commercial platform gaining enterprise traction with 71% revenue growth',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional buying but no specific mega-HF cluster buy visible in Q1 2026 13F data',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$130-$145',
    'price_target': '$220',
    'stop_loss': '$108',
    'thesis_hold_conditions': 'Hold as long as: US commercial revenue growth above 60% YoY; DoD contracts expanding to new agencies; AIP enterprise deployments growing; Maven AI remains embedded in military operations',
    'thesis_break_triggers': 'EXIT if: DoD cancels or materially reduces Maven program OR DIA contract dispute results in permanent agency exclusion OR US commercial revenue decelerates below 40% for 2 consecutive quarters OR Karp sells >$100M in a single month (stress signal)',
    'key_catalysts': 'Q2 earnings Aug 4 (11 days; US commercial +104% YoY trend); Maven expansion to classified networks; AIP commercial wins; $10B Army contract milestones',
    'key_risks': 'Extreme valuation (150x forward PE); active DIA contract dispute; political risk of DoD AI expansion; Karp personal brand risk',
    'analyst_note': 'PLTR is the only pure-play AI defense/analytics company, and the Q1 print (+85% total revenue, +104% US commercial) confirmed the AIP commercial inflection. The DoD relationships are not contracts — they are embedded in operational workflows with switching costs measured in mission risk. The DIA dispute is noise; the Army $10B enterprise agreement is signal. At 150x forward PE, this is not cheap, but software-defined defense AI with 71% revenue growth and government lock-in deserves a premium. The upcoming Q2 earnings on August 4 are the next catalyst — expect another US commercial upside print.',
  },
  {
    'symbol': 'NOW', 'company': 'ServiceNow Inc.', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 66, 'close': 1085.0,
    'rs_vs_spy_20d': 0.029, 'pct_from_52w_high': -0.08, 'volume_ratio': 1.2,
    'ai_category': 'AI Software/Enterprise',
    'valuation': {'forwardPE': 55, 'peg': 1.9, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider buys; CEO McDermott compensation plan tied to AI revenue targets',
    'short_interest_pct': 0.018, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-22', 'earnings_days_away': 2, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Q2 earnings play; large call sweeps $1100-$1150 strikes; NOW Assist AI revenue the swing factor',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Analysts bullish ahead of Q2; NOW Assist AI revenue $1.5B target is the key metric; 21% subscription growth vs Salesforce 0.21% — divergence widens',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'NONE',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Enterprise workflow automation with 90%+ renewal rates; Now Assist AI embedding in every workflow = sticky price increases; government/defense contracts lock-in at enterprise scale',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership; no specific mega-fund entry signal',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$1020-$1090',
    'price_target': '$1350',
    'stop_loss': '$880',
    'thesis_hold_conditions': 'Hold as long as: subscription growth above 20% YoY; Now Assist AI revenue growing >100% YoY; renewal rates above 97%; enterprise deal sizes increasing',
    'thesis_break_triggers': 'EXIT if: NOW Assist AI revenue misses $1.5B target by >20% OR subscription growth decelerates below 15% for 2 consecutive quarters OR Microsoft Copilot makes material inroads into NOW workflow market',
    'key_catalysts': 'Q2 earnings imminent; Now Assist AI revenue print; EmployeeWorks adoption; government workflow automation contracts',
    'key_risks': 'Q2 earnings risk; Microsoft Copilot competitive overlap; high valuation; CEO change risk (McDermott is the brand)',
    'analyst_note': 'NOW is the highest-quality pure-play AI enterprise software name: 21% subscription growth when Salesforce is at 0.21% tells you everything about execution divergence. The Now Assist AI layer is being embedded into every ServiceNow workflow, creating an AI monetization engine that compounds as enterprises automate more processes. McDermott raised the AI revenue target to $1.5B last quarter — if Q2 delivers on that trajectory, this stock goes meaningfully higher. The rotation into software explicitly favors NOW.',
  },
  {
    'symbol': 'CEG', 'company': 'Constellation Energy Corp.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 65, 'close': 345.0,
    'rs_vs_spy_20d': 0.035, 'pct_from_52w_high': -0.06, 'volume_ratio': 1.25,
    'ai_category': 'AI Power/Nuclear',
    'valuation': {'forwardPE': 28, 'peg': 1.4, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider buys/sells; management compensation tied to contracted revenue milestones',
    'short_interest_pct': 0.022, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-06', 'earnings_days_away': 13, 'earnings_risk': 'EARNINGS_NEAR',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal options activity; institutional positioning steady',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Multiple upgrades post Calpine acquisition (doubled quarterly rev to $11.1B); nuclear data center theme driving Street upgrades',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'NONE',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': '5,650 MW in long-term clean energy contracts with hyperscalers; 20-year PPAs with Microsoft (Three Mile Island) and Meta (1.1 GW) — annuity revenue streams; Calpine acquisition added 21,000 MW gas/geothermal; nuclear baseload has zero fuel cost volatility and unmatched capacity factor (92-95%)',
    'smart_money_13f': 'SMART_MONEY_ACCUMULATING',
    'smart_money_detail': 'Energy-focused HFs and Situational Awareness LP accumulating AI power plays; CEG is the flagship nuclear AI power name',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$320-$350',
    'price_target': '$430',
    'stop_loss': '$270',
    'thesis_hold_conditions': 'Hold as long as: hyperscaler nuclear PPA demand continues; nuclear regulatory environment stable; Calpine integration on track; electricity prices in PJM/ERCOT supportive',
    'thesis_break_triggers': 'EXIT if: Microsoft or Meta cancel nuclear PPAs OR nuclear regulatory setback forces plant closure OR natural gas prices collapse below $2 (removes nuclear premium) OR antitrust forces Calpine divestiture',
    'key_catalysts': 'Q2 earnings Aug 6 (first full quarter with Calpine); new hyperscaler PPA announcement; DOE SMR licensing progress; Three Mile Island output ramp',
    'key_risks': 'NRC regulatory risk; Calpine integration complexity; rising interest rates increase cost of nuclear maintenance capital; valuation elevated',
    'analyst_note': 'CEG is the only utility that is actually a technology infrastructure company in disguise: 5,650 MW in locked hyperscaler contracts, a just-completed acquisition of Calpine that nearly doubles its scale, and the Three Mile Island restart as proof of concept for nuclear data center power. The 20-year PPAs with Microsoft and Meta are not utility contracts — they are AI infrastructure annuities. In a rising-rate environment that hurts most utilities, CEG\'s fixed-rate long-term contracts protect cash flow. This is the best risk-adjusted AI play for investors who want minimal hardware/semiconductor exposure.',
  },
  {
    'symbol': 'VST', 'company': 'Vistra Corp.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 67, 'close': 198.0,
    'rs_vs_spy_20d': 0.043, 'pct_from_52w_high': -0.04, 'volume_ratio': 1.3,
    'ai_category': 'AI Power/Nuclear',
    'valuation': {'forwardPE': 22, 'peg': 1.2, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material Form 4 buys or sells recently',
    'short_interest_pct': 0.028, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-05', 'earnings_days_away': 12, 'earnings_risk': 'EARNINGS_NEAR',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Steady institutional positioning; no unusual sweeps',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Multiple upgrades after Meta 2,600 MW nuclear PPA closed Jan 2026; AI power theme driving reratings',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'NONE',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': '20-year PPA with Meta for ~2,600 MW of nuclear power across three PJM plants — locked-in electricity pricing with the world\'s largest data center builder; nuclear baseload capacity factors >92% vs 25-30% for wind/solar; ERCOT market presence provides additional price optionality',
    'smart_money_13f': 'SMART_MONEY_ACCUMULATING',
    'smart_money_detail': 'Situational Awareness LP (Leopold Aschenbrenner fund) doubled AUM in Q1 2026 and is explicitly bullish on AI power/energy names; VST is a core position',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$185-$200',
    'price_target': '$255',
    'stop_loss': '$155',
    'thesis_hold_conditions': 'Hold as long as: Meta 20-year PPA intact and payments current; Texas ERCOT prices supportive; nuclear capacity factors above 90%; additional hyperscaler PPA negotiations progressing',
    'thesis_break_triggers': 'EXIT if: Meta cancels or restructures the 2,600 MW PPA OR ERCOT market structure changes negatively OR nuclear plant forced shutdown for safety/regulatory reasons OR natural gas collapses below $2 for 12+ months (reduces VST competitive advantage)',
    'key_catalysts': 'Q2 earnings Aug 5; first full quarter of Meta PPA revenue; potential second hyperscaler PPA announcement; ERCOT capacity auction results',
    'key_risks': 'Single-customer concentration risk (Meta = largest revenue source); rate environment impact on cost of capital; Texas regulatory risk; valuation premium to traditional utilities',
    'analyst_note': 'VST is the cleanest expression of the AI power theme after CEG: a 20-year, 2,600 MW nuclear PPA with Meta signed January 2026 transforms VST from a commodity power generator into a contracted AI infrastructure provider. Leopold Aschenbrenner\'s Situational Awareness LP doubled its AUM in Q1 2026 with explicit long positions in AI power names — this is the smart money reading the power constraint correctly. In the current rotation, VST is a flight to quality: growth without tech-sector volatility.',
  },
  {
    'symbol': 'AMAT', 'company': 'Applied Materials Inc.', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 56, 'close': 185.0,
    'rs_vs_spy_20d': -0.015, 'pct_from_52w_high': -0.12, 'volume_ratio': 1.1,
    'ai_category': 'Semiconductor Equipment',
    'valuation': {'forwardPE': 21, 'peg': 0.8, 'vs_peers': 'CHEAP'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider trades; management compensation tied to equipment revenue backlog',
    'short_interest_pct': 0.028, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-13', 'earnings_days_away': 20, 'earnings_risk': 'LOW',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal equipment sector positioning; no unusual sweeps',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Analysts noting TSMC capex + INTC 18A ramp = multi-year AMAT tailwind; FY2026 EPS $12.27 (+27.6% YoY)',
    'news_sentiment': 'NEUTRAL',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'HIGH',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'CVD/PVD/ALD equipment essential for N2 and A16 nodes; TSMC sole-sourced AMAT deposition systems for CoWoS packaging; no viable alternative supplier for gate-all-around transistor formation',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership; no specific new mega-position signals',
    'sector_rotation_impact': 'DISFAVORED',
    'buy_zone': '$172-$188',
    'price_target': '$240',
    'stop_loss': '$148',
    'thesis_hold_conditions': 'Hold as long as: TSMC capex above $55B annually; INTC 18A ramp progressing; memory capex for HBM4 expanding; China equipment restrictions not broadened to AMAT core products',
    'thesis_break_triggers': 'EXIT if: TSMC guides capex cut >20% OR China export controls expand to cover AMAT core deposition systems OR semiconductor capex broadly cuts (2 major customers guide down)',
    'key_catalysts': 'Q4 FY2026 earnings Aug 13; TSMC N2 capex update; Intel 18A yield progress; CHIPS Act secondary investments through TSMC/INTC',
    'key_risks': 'Hardware sector rotation headwind; China equipment restrictions could expand; cyclical semicap demand risk if hyperscaler capex moderates',
    'analyst_note': 'AMAT is collateral damage from the AI hardware selloff, but the fundamental story is intact: every TSMC N2 wafer and Intel 18A chip requires AMAT deposition equipment. At PEG 0.8, this is the cheapest large-cap name in the AI supply chain. The near-term rotation headwind is real, but patient buyers at current levels will be rewarded when the semiconductor equipment upcycle resumes. FY2026 EPS of $12.27 (+27.6%) is not priced in at current multiples.',
  },
  {
    'symbol': 'NVDA', 'company': 'NVIDIA Corporation', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 56, 'close': 207.81,
    'rs_vs_spy_20d': -0.025, 'pct_from_52w_high': -0.12, 'volume_ratio': 1.8,
    'ai_category': 'Chips/AI Infrastructure',
    'valuation': {'forwardPE': 38, 'peg': 1.5, 'vs_peers': 'FAIR'},
    'insider_activity': 'BEARISH',
    'insider_detail': 'Director Mark Stevens sold 885K shares at $209-210 on June 18, 2026; net $15.6B in insider selling across NVDA/PLTR/META trailing 3 years; no insider buying visible — note this is insider SELLING while stock is near highs (not a red flag per se but worth monitoring)',
    'short_interest_pct': 0.017, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-20', 'earnings_days_away': 27, 'earnings_risk': 'LOW',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Mixed options activity; put buying increased during July selloff alongside call volume',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Consensus overwhelmingly bullish; PTs range $180-$350; near-term headwinds acknowledged but 12-month targets uniformly higher',
    'news_sentiment': 'NEUTRAL',
    'social_sentiment': 'BULLISH',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'EXTREME',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'PRICING_LEADER',
    'pricing_power_detail': 'CUDA software ecosystem = 15-year moat; GB300 demand "off the charts" per Jensen; $500B purchase commitments outstanding; supply constrained through 2026; no meaningful GPU competitor for training workloads; NVLink backplane creates closed-system pricing power for HPC clusters',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'NVDA was the #1 13F add (+$187.2B) across the universe in Q1 2026; but Baillie Gifford taking profits at higher levels; net mixed — institutions adding on dips, some trimming at highs',
    'sector_rotation_impact': 'DISFAVORED',
    'buy_zone': '$190-$210',
    'price_target': '$275',
    'stop_loss': '$162',
    'thesis_hold_conditions': 'Hold as long as: GB300/GB200 demand supply-constrained; CUDA remains the dominant AI training framework; hyperscaler capex commitments for NVDA are intact; gross margins above 72%',
    'thesis_break_triggers': 'EXIT if: 2+ hyperscalers publicly announce shifting >30% of AI training capex to non-NVDA silicon OR CUDA open-source alternatives (ROCm, OpenXLA) reach training performance parity OR gross margins decline below 68% for 2 consecutive quarters OR China export restrictions escalate to ban all NVDA products',
    'key_catalysts': 'Q2 FY2027 earnings Aug 20; GB300 shipment volume update; Vera Rubin platform announcement; NVDA Compute platform (challenge to AWS/Azure)',
    'key_risks': 'Sector rotation disfavored; insider selling at highs; 25% tariff on China chip exports reducing TAM; $38 PEG still elevated; AVGO custom silicon displacing some NVDA inference workloads',
    'analyst_note': 'NVDA is the most controversial stock in this watchlist: fundamentally exceptional (GB300 demand off the charts, $500B committed backlog, $65B Q4 guidance), but the rotation is explicitly working against it and insiders are selling at $209-210. The CUDA moat is real and likely unbreakable for training workloads through 2028, but the multiple compression from rising yields (4.71% 10yr) is equally real. This is a HOLD for existing positions, not a new buy at current prices. Let the sector rotation play out; the next compelling entry is the Aug 20 earnings print if the selloff persists. Avoid chasing.',
  },
  {
    'symbol': 'MU', 'company': 'Micron Technology Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 47, 'close': 98.0,
    'rs_vs_spy_20d': -0.042, 'pct_from_52w_high': -0.18, 'volume_ratio': 2.1,
    'ai_category': 'Memory/HBM',
    'valuation': {'forwardPE': 14, 'peg': 0.6, 'vs_peers': 'CHEAP'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material Form 4 buys; CEO Sanjay Mehrotra compensation tied to HBM4 revenue milestones',
    'short_interest_pct': 0.055, 'squeeze_risk': 'HIGH',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-09-24', 'earnings_days_away': 62, 'earnings_risk': 'LOW',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Put buying increased during July selloff; some call covering; mixed but not alarming',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Analysts bullish post HBM4 volume production announcement; multiple upgrades citing Vera Rubin sole-source status; avg PT ~$150',
    'news_sentiment': 'NEUTRAL',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'MEDIUM',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'HBM4 sole-source certification for NVDA Vera Rubin (Samsung disqualified on quality); HBM4 ramping 2x faster than HBM3E; 2026 supply fully contracted; only MU and SK Hynix are qualified HBM4 suppliers — duopoly pricing through at least 2027; gross margins expanding toward 38%',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Situational Awareness LP bearish overlay on first-order chip names in Q1 2026 — a specific red flag for MU; broader 13F data shows mixed institutional positioning',
    'sector_rotation_impact': 'DISFAVORED',
    'buy_zone': '$90-$105',
    'price_target': '$155',
    'stop_loss': '$76',
    'thesis_hold_conditions': 'Hold as long as: Samsung remains disqualified from HBM4 for NVDA; NVDA Vera Rubin ramp on schedule; AI HBM demand exceeds MU+SK Hynix combined supply; gross margins expanding',
    'thesis_break_triggers': 'EXIT if: Samsung re-qualifies for HBM4 supply to NVDA OR NVDA delays Vera Rubin by >2 quarters OR 2+ hyperscalers cut AI capex guidance materially OR PC/mobile DRAM demand collapses (margin dilution)',
    'key_catalysts': 'HBM4 2027 supply allocation updates; Vera Rubin platform launch volume; Q4 FY2026 earnings September 24; CHIPS Act disbursement milestone',
    'key_risks': 'Samsung re-qualification is the #1 thesis risk; sector rotation disfavored; stock already down 13-18% from peak in July selloff; smart money bearish overlay (Situational Awareness LP)',
    'analyst_note': 'MU is the best risk/reward setup in this watchlist: PEG 0.6, CHEAP valuation, HBM4 sole-source for the most critical AI memory application in existence (NVDA Vera Rubin), and a 2x-faster-than-expected ramp. The -13% July selloff is entirely rotation-driven — the fundamental data (HBM4 in mass production, 2026 fully allocated, 2027 in discussion) is the strongest of any period in MU\'s history. The risk is Samsung re-qualification — if that headline hits, exit immediately. Until then, the dip is a gift. Situational Awareness LP\'s bearish chip overlay is a legitimate concern but appears to be a macro/valuation call, not a fundamental call specific to MU.',
  },
  {
    'symbol': 'ANET', 'company': 'Arista Networks Inc.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 63, 'close': 378.0,
    'rs_vs_spy_20d': 0.008, 'pct_from_52w_high': -0.09, 'volume_ratio': 1.15,
    'ai_category': 'Networking/AI Infrastructure',
    'valuation': {'forwardPE': 42, 'peg': 1.8, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider trades; Jayshree Ullal compensation tied to revenue and AI cluster market share',
    'short_interest_pct': 0.018, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-08-04', 'earnings_days_away': 11, 'earnings_risk': 'EARNINGS_NEAR',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Unusual call sweep ahead of Aug 4 earnings; $390-$410 strikes, 30d expiry',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Q1 revenue $2.71B (+35.1% YoY), raised FY2026 to $11.5B; analysts raising PTs uniformly; 800G/1.6T optical transition is the next catalyst',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'NONE',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'EOS network operating system with 90%+ customer retention in hyperscaler AI clusters; 800G Ethernet switching the standard for current-gen AI infrastructure; customers cannot switch without retraining their entire network operations team — switching cost is 2-3 years of operational disruption',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Stable institutional ownership; no specific mega-fund entries or exits visible',
    'sector_rotation_impact': 'NEUTRAL',
    'buy_zone': '$350-$382',
    'price_target': '$475',
    'stop_loss': '$298',
    'thesis_hold_conditions': 'Hold as long as: AI cluster build-outs require Ethernet networking; 800G/1.6T transition ongoing; gross margins above 62%; hyperscaler network capex growing',
    'thesis_break_triggers': 'EXIT if: InfiniBand regains dominant AI cluster share from Ethernet OR hyperscaler capex for networking specifically cuts >20% OR EOS renewal rates fall below 85%',
    'key_catalysts': 'Q2 earnings Aug 4 (11 days); 800G adoption update; AI cluster win at new hyperscaler; 1.6T Terabit switching timeline',
    'key_risks': 'Cisco competitive response; InfiniBand (NVDA) vs Ethernet battle resolution; near-term hardware rotation headwind',
    'analyst_note': 'ANET is the most defensible network infrastructure play: the EOS software stack creates a lock-in that is comparable to NVDA CUDA for networking. With FY2026 raised to $11.5B (+28% YoY) and the 800G transition just beginning, the next leg of growth is 1.6T adoption in 2027. Earnings on August 4 are 11 days away — the setup into the print is favorable given the Q1 beat and raised guidance pattern. Hold through earnings.',
  },
  {
    'symbol': 'LRCX', 'company': 'Lam Research Corporation', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 58, 'close': 82.0,
    'rs_vs_spy_20d': -0.018, 'pct_from_52w_high': -0.14, 'volume_ratio': 1.2,
    'ai_category': 'Semiconductor Equipment',
    'valuation': {'forwardPE': 19, 'peg': 0.7, 'vs_peers': 'CHEAP'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider trades; Tim Archer compensation tied to etch/deposition equipment revenue',
    'short_interest_pct': 0.033, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-29', 'earnings_days_away': 5, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Pre-earnings positioning; mixed call/put activity',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Fastest-growing large-cap semicap (+26.5% TTM revenue); EPS est $1.68 for Q2 vs $1.47 last; semicap earnings forecast to surge +133% in Q2',
    'news_sentiment': 'NEUTRAL',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'DIRECT_BENEFICIARY',
    'taiwan_signal': 'POSITIVE',
    'taiwan_exposure': 'HIGH',
    'govt_catalyst': 'PENDING',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Etch and deposition equipment essential for NAND, DRAM, and leading-edge logic; TSMC N2 and HBM4 DRAM production require LRCX-specific process steps; sole-source position on selective etch for gate-all-around transistors',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership; no concentrated HF entries',
    'sector_rotation_impact': 'DISFAVORED',
    'buy_zone': '$76-$84',
    'price_target': '$110',
    'stop_loss': '$62',
    'thesis_hold_conditions': 'Hold as long as: TSMC/Micron memory capex above $30B annually; HBM4 production requiring LRCX etch steps; leading-edge logic shrink continuing; China restrictions not expanding to LRCX core etch tools',
    'thesis_break_triggers': 'EXIT if: TSMC announces capex cut >25% OR China export restrictions expand to LRCX selective etch tools (currently not restricted) OR NAND/DRAM capex broadly contracts for 2+ quarters',
    'key_catalysts': 'Q4 FY2026 earnings July 29 (5 days); Micron HBM4 etch tool order update; TSMC N2 volume ramp equipment cadence',
    'key_risks': 'Hardware rotation headwind; China equipment risks; earnings 5 days away (event risk); -14% from 52-week high (technical damage)',
    'analyst_note': 'LRCX is the fastest-growing large-cap semiconductor equipment company at +26.5% TTM revenue, driven by HBM4 and N2 process complexity. At PEG 0.7 with earnings in 5 days, this is a high-risk/high-reward setup: a beat would drive meaningful upside from current depressed levels; a miss or soft guide would extend the selloff. For investors with a 6-12 month horizon, buying LRCX at -14% from highs with HBM4 ramp intact is a strong risk/reward. The rotation headwind is temporary.',
  },
  {
    'symbol': 'VRT', 'company': 'Vertiv Holdings Co.', 'is_core': True,
    'filter_status': 'PASSED', 'quant_score': 64, 'close': 122.0,
    'rs_vs_spy_20d': 0.015, 'pct_from_52w_high': -0.07, 'volume_ratio': 1.2,
    'ai_category': 'AI Infrastructure/Cooling',
    'valuation': {'forwardPE': 35, 'peg': 1.6, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider trades; CEO Giordano compensation tied to data center revenue and backlog',
    'short_interest_pct': 0.038, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-30', 'earnings_days_away': 6, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'BULLISH_OPTIONS',
    'options_detail': 'Call activity ahead of July 30 earnings; $125-$135 strike; institutional positioning bullish',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Management raised FY2026 to $13.5-14B, adj EPS $6.30-6.40 (vs $6.08 consensus); 30% organic growth, 51% EPS growth',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'NONE',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Liquid cooling is mandatory for Blackwell GPU systems (>1000W TDP); VRT is the largest commercial liquid cooling provider by revenue and patent count; $15B backlog provides 1+ year of revenue visibility; data center operators cannot retrofit liquid cooling — new builds specify VRT at design phase',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership; growing interest from AI infrastructure-focused funds',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$112-$124',
    'price_target': '$158',
    'stop_loss': '$92',
    'thesis_hold_conditions': 'Hold as long as: AI data center buildout continues; Blackwell TDP requirement driving liquid cooling adoption; backlog above $12B; gross margins expanding above 36%',
    'thesis_break_triggers': 'EXIT if: NVDA Rubin/Blackwell GPUs redesigned to allow air cooling (physically impossible at current TDP) OR hyperscaler capex cuts reduce data center construction starts by >30% OR VRT loses a major data center customer to a competitor',
    'key_catalysts': 'Q2 earnings July 30 (6 days); backlog update; new liquid cooling customer wins; Blackwell data center deployment count',
    'key_risks': 'Earnings in 6 days (event risk); high valuation; raw material cost inflation; competition from custom in-house cooling from hyperscalers',
    'analyst_note': 'VRT is the purest play on the physical constraint of AI compute: GPUs are getting hotter and only liquid cooling works at Blackwell TDP levels. The $15B backlog at 30% organic growth and 51% EPS growth should silence any valuation bears. With earnings in 6 days and the rotation explicitly favoring industrial/infrastructure plays over hardware, the setup is favorable. Buy on any weakness below $120.',
  },
  {
    'symbol': 'PWR', 'company': 'Quanta Services Inc.', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 65, 'close': 345.0,
    'rs_vs_spy_20d': 0.022, 'pct_from_52w_high': -0.06, 'volume_ratio': 1.15,
    'ai_category': 'AI Infrastructure/Power Grid',
    'valuation': {'forwardPE': 26, 'peg': 1.3, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material insider trades; management compensation aligned with backlog growth',
    'short_interest_pct': 0.018, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-31', 'earnings_days_away': 7, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal options activity; no unusual sweeps',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Q1 $7.87B (+26.3%), EPS $2.68 vs $2.04 est; raised FY2026 to $34.7-35.2B; $48.5B backlog (+45.3% YoY)',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'NONE',
    'govt_catalyst': 'NONE',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Largest electrical infrastructure contractor in North America; $48.5B backlog = 16+ months of visibility; AI data center power connections require specialized high-voltage expertise that only Quanta and 1-2 others can deliver; hyperscalers must use PWR for grid interconnection',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Infrastructure-focused institutional buyers; growing HF interest in AI power grid theme',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$320-$348',
    'price_target': '$420',
    'stop_loss': '$270',
    'thesis_hold_conditions': 'Hold as long as: data center construction starts above 500MW/quarter in North America; utility power grid modernization spending growing; backlog stays above $40B; project margins expanding',
    'thesis_break_triggers': 'EXIT if: hyperscaler data center construction freezes for 2+ quarters OR material labor shortage causes project cost overruns OR government infrastructure spending cuts affect utility budgets',
    'key_catalysts': 'Q2 earnings July 31; backlog update; data center power connection order announcements; utility grid modernization contract awards',
    'key_risks': 'Earnings in 7 days (event risk); labor market tightness could impact margins; project timing risk; valuation premium to traditional contractors',
    'analyst_note': 'PWR is the invisible backbone of the AI buildout: you cannot build a data center without connecting it to the grid, and Quanta is the only company with the scale and certified workforce to do it at hyperscaler speed. The $48.5B backlog (+45.3% YoY) is the strongest forward visibility in this entire watchlist. In the current rotation away from hardware, industrial infrastructure like PWR is the rational destination.',
  },
  {
    'symbol': 'ETN', 'company': 'Eaton Corporation plc', 'is_core': False,
    'filter_status': 'PASSED', 'quant_score': 60, 'close': 352.0,
    'rs_vs_spy_20d': 0.010, 'pct_from_52w_high': -0.08, 'volume_ratio': 1.1,
    'ai_category': 'AI Infrastructure/Power Mgmt',
    'valuation': {'forwardPE': 29, 'peg': 1.5, 'vs_peers': 'FAIR'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'No material Form 4 activity; Craig Arnold compensation tied to EV and data center electrical revenue',
    'short_interest_pct': 0.015, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_UP',
    'earnings_date': '2026-07-29', 'earnings_days_away': 5, 'earnings_risk': 'HIGH_EVENT_RISK',
    'options_flow': 'NEUTRAL',
    'options_detail': 'Normal pre-earnings positioning',
    'analyst_action': 'UPGRADED',
    'analyst_detail': 'Q1 revenue +30% to $2.65B; raised FY2026 to $13.5-14B; data center electrical equipment demand exceeding supply',
    'news_sentiment': 'BULLISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'NONE',
    'govt_catalyst': 'NONE',
    'pricing_power': 'STRONG_POSITION',
    'pricing_power_detail': 'Electrical switchgear, UPS systems, and power distribution essential for every data center; PDU and busway products have 18-24 month lead times; data center operators cannot substitute ETN electrical infrastructure once specified in building design',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'Broad institutional ownership in industrial sector; AI data center theme driving new interest',
    'sector_rotation_impact': 'FAVORED',
    'buy_zone': '$330-$355',
    'price_target': '$420',
    'stop_loss': '$278',
    'thesis_hold_conditions': 'Hold as long as: data center electrical equipment backlog growing; AI data center construction starts above 400MW/quarter; gross margins above 38%',
    'thesis_break_triggers': 'EXIT if: hyperscaler data center construction halts for 2+ quarters OR supply chain normalizes and lead times compress below 6 months (pricing power erosion) OR EV/grid segment disappoints for 2+ quarters',
    'key_catalysts': 'Q2 earnings July 29 (5 days); data center electrical backlog update; EV charging infrastructure contract awards',
    'key_risks': 'Earnings in 5 days; supply chain normalization risk; EV segment slower than expected; valuation elevated',
    'analyst_note': 'ETN is the electrical infrastructure equivalent of VRT: essential equipment that every AI data center requires before it can turn on a single GPU. The Q1 +30% revenue growth and raised FY2026 guidance confirms the thesis. At PEG 1.5 with 30% revenue growth and 5-day earnings catalyst, the risk/reward is favorable. The current sector rotation explicitly favors ETN over hardware names.',
  },
  {
    'symbol': 'ORCL', 'company': 'Oracle Corporation', 'is_core': True,
    'filter_status': 'CORE_OVERRIDE', 'quant_score': 46, 'close': 162.0,
    'rs_vs_spy_20d': -0.038, 'pct_from_52w_high': -0.19, 'volume_ratio': 1.4,
    'ai_category': 'Cloud/AI Software',
    'valuation': {'forwardPE': 32, 'peg': 2.8, 'vs_peers': 'EXPENSIVE'},
    'insider_activity': 'NEUTRAL',
    'insider_detail': 'Larry Ellison on structured diversification plan; no unusual insider buying signals',
    'short_interest_pct': 0.02, 'squeeze_risk': 'LOW',
    'earnings_revision': 'REVISIONS_DOWN',
    'earnings_date': '2026-09-10', 'earnings_days_away': 48, 'earnings_risk': 'LOW',
    'options_flow': 'BEARISH_OPTIONS',
    'options_detail': 'Put buying elevated; institutions buying downside protection; bearish options flow in July',
    'analyst_action': 'NEUTRAL',
    'analyst_detail': 'Mixed analyst views; some downgrading on OpenAI dependency; bearish thesis gaining traction on cloud margin risk',
    'news_sentiment': 'BEARISH',
    'social_sentiment': 'NEUTRAL',
    'tech_impact': 'INDIRECT',
    'taiwan_signal': 'NEUTRAL',
    'taiwan_exposure': 'LOW',
    'govt_catalyst': 'CONFIRMED',
    'pricing_power': 'COMPETITIVE',
    'pricing_power_detail': 'Database legacy moat eroding as Snowflake/Databricks take cloud analytics share; cloud infrastructure growth slower than AWS/Azure/GCP; OpenAI is largest cloud customer and its rent payment risk is real — if OpenAI fundraise slows, ORCL cloud revenue at risk',
    'smart_money_13f': 'SMART_MONEY_NEUTRAL',
    'smart_money_detail': 'No notable smart money accumulation signals; some HFs reducing ORCL exposure',
    'sector_rotation_impact': 'NEUTRAL',
    'buy_zone': 'AVOID NEW POSITIONS',
    'price_target': '$185',
    'stop_loss': '$138',
    'thesis_hold_conditions': 'Hold ONLY if: OpenAI continues to make rent payments; cloud revenue growth re-accelerates above 25% YoY; database legacy business stabilizes',
    'thesis_break_triggers': 'EXIT if: OpenAI misses payment obligations to ORCL OR cloud revenue growth below 15% for 2 consecutive quarters OR Snowflake/Databricks sign away 2+ ORCL enterprise database customers',
    'key_catalysts': 'DoD/government cloud expansion; OpenAI fundraise success; Q1 FY2027 earnings September',
    'key_risks': 'OpenAI dependency (single customer concentration risk); cloud infrastructure behind AWS/Azure/GCP; REVISIONS_DOWN is the loudest warning signal in this analysis; PEG 2.8 EXPENSIVE',
    'analyst_note': 'AVOID NEW POSITIONS. ORCL is the weakest CORE stock and the only name in this watchlist with REVISIONS_DOWN. The thesis depends on OpenAI continuing to make rent payments on ORCL\'s AI data centers — that is not a business thesis, it is a receivables risk. Cloud growth is slowing while AWS/Azure/GCP accelerate. Database legacy moat is eroding. The DoD contract is real but insufficient to offset the OpenAI concentration risk. If you own ORCL, the thesis break trigger is an OpenAI payment issue — set your alert and be ready to exit.',
  },
]

all_candidates = raw

# ── PHASE 7: SCORING ──────────────────────────────────────────────────────────
for candidate in all_candidates:
    qs  = candidate.get('quant_score', 50)
    val = {'CHEAP':80,'FAIR':50,'EXPENSIVE':20}.get(candidate.get('valuation',{}).get('vs_peers','FAIR'),50)
    ins = {'BULLISH_INSIDER':100,'BULLISH':100,'NEUTRAL':50,'BEARISH_INSIDER':20,'BEARISH':20}.get(candidate.get('insider_activity','NEUTRAL'),50)
    rev = {'REVISIONS_UP':100,'STABLE':50,'REVISIONS_DOWN':20}.get(candidate.get('earnings_revision','STABLE'),50)
    opt = {'BULLISH_OPTIONS':80,'NEUTRAL':50,'BEARISH_OPTIONS':20}.get(candidate.get('options_flow','NEUTRAL'),50)
    ana = {'UPGRADED':90,'INITIATED':60,'NEUTRAL':50,'DOWNGRADED':20}.get(candidate.get('analyst_action','NEUTRAL'),50)
    nws = {'BULLISH':80,'NEUTRAL':50,'BEARISH':20}.get(candidate.get('news_sentiment','NEUTRAL'),50)
    soc = {'BULLISH':80,'NEUTRAL':50,'BEARISH':20}.get(candidate.get('social_sentiment','NEUTRAL'),50)
    tec = {'DIRECT_BENEFICIARY':100,'INDIRECT':50,'THREATENED':0}.get(candidate.get('tech_impact','INDIRECT'),50)
    twn = {'POSITIVE':100,'NEUTRAL':50,'RISK':20}.get(candidate.get('taiwan_signal','NEUTRAL'),50)
    gov = {'CONFIRMED':100,'PENDING':75,'NONE':50,'POLITICAL_RISK':25}.get(candidate.get('govt_catalyst','NONE'),50)
    mac = 100 if macro_summary.get('vix',25)<20 else 50
    prc = {'PRICING_LEADER':100,'STRONG_POSITION':75,'COMPETITIVE':50,'COMMODITY_RISK':20}.get(candidate.get('pricing_power','COMPETITIVE'),50)
    smf = {'SMART_MONEY_ACCUMULATING':100,'SMART_MONEY_NEUTRAL':50,'SMART_MONEY_EXITING':20}.get(candidate.get('smart_money_13f','SMART_MONEY_NEUTRAL'),50)
    sym = candidate.get('symbol','')
    rot = 100 if sym in rotation_summary.get('rotation_favored',[]) else 20 if sym in rotation_summary.get('rotation_disfavored',[]) else 60
    candidate['sector_rotation_impact'] = 'FAVORED' if rot==100 else 'DISFAVORED' if rot==20 else 'NEUTRAL'
    candidate['final_score'] = round(
        qs*0.20 + val*0.03 + ins*0.10 + rev*0.10 + opt*0.03 + ana*0.03 +
        nws*0.05 + soc*0.03 + tec*0.10 + twn*0.10 + gov*0.10 + mac*0.03 +
        prc*0.08 + smf*0.07 + rot*0.05, 1)
    candidate['conviction'] = 'HIGH' if candidate['final_score']>=75 else 'MEDIUM' if candidate['final_score']>=55 else 'LOW'

all_candidates = [c for c in all_candidates if c.get('final_score',0)>=40 or c.get('is_core')]
all_candidates.sort(key=lambda x: x.get('final_score',0), reverse=True)
all_candidates = all_candidates[:30]
for i, c in enumerate(all_candidates, 1):
    c['rank'] = i

print(f"Phase 7 complete: {len(all_candidates)} candidates ranked")
for c in all_candidates:
    print(f"  #{c['rank']:2d} {c['symbol']:6s} score={c['final_score']:.1f} [{c['conviction']}]")

# ── PHASE 8: WRITE FILES ──────────────────────────────────────────────────────
watchlist_data = {
    'generated_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'analyst_confidence': 'HIGH' if len([c for c in all_candidates if c.get('conviction')=='HIGH']) >= 5 else 'MEDIUM',
    'market_regime': macro_summary.get('market_regime', 'UNKNOWN'),
    'vix': macro_summary.get('vix', 0),
    'treasury_10yr': macro_summary.get('treasury_10yr', 0),
    'dxy': macro_summary.get('dxy', 0),
    'copper_trend': macro_summary.get('copper_trend', 'UNKNOWN'),
    'etf_flows': etf_flow_dict,
    'sector_rotation_today': rotation_summary.get('sector_rotation_today', 'NO_CLEAR_ROTATION'),
    'rotation_favored': rotation_summary.get('rotation_favored', []),
    'rotation_disfavored': rotation_summary.get('rotation_disfavored', []),
    'macro_themes': macro_summary.get('macro_themes', []),
    'emerging_tech_themes': macro_summary.get('emerging_tech_themes', []),
    'taiwan_signals': macro_summary.get('taiwan_signals', []),
    'govt_catalysts': macro_summary.get('govt_catalysts', []),
    'cross_strait_risk': macro_summary.get('cross_strait_risk', 'MEDIUM'),
    'candidates': all_candidates,
}

with open('/home/user/watchlist.json', 'w', encoding='utf-8') as f:
    json.dump(watchlist_data, f, indent=2)
print(f'watchlist.json written: {len(all_candidates)} candidates')

# ── SCAN LOG ──────────────────────────────────────────────────────────────────
today = date.today().isoformat()
top5 = all_candidates[:5]

lines = [
    f'# Pre-Market Briefing — {today}',
    '',
    f'**Market:** {macro_summary.get("market_regime","?")} | VIX {macro_summary.get("vix",0):.1f} | 10yr {macro_summary.get("treasury_10yr",0):.2f}% | DXY {macro_summary.get("dxy",0):.1f} | SPY 5d {macro_summary.get("spy_5d_return",0)*100:.1f}%',
    f'**Rotation:** {rotation_summary.get("sector_rotation_today","?")}',
    f'**Rotation Favored:** {", ".join(rotation_summary.get("rotation_favored",[]))}',
    f'**Rotation Disfavored:** {", ".join(rotation_summary.get("rotation_disfavored",[]))}',
    '',
    '---',
    '',
    '## Macro Context',
    '',
]
for theme in macro_summary.get('macro_themes', []):
    lines.append(f'- {theme}')

lines += ['', '## Top 5 Candidates', '']
for c in top5:
    hold = c.get('thesis_hold_conditions','—')
    xit  = c.get('thesis_break_triggers','—')
    lines.append(f'### #{c["rank"]} {c["symbol"]} — Score {c.get("final_score",0):.1f} [{c.get("conviction","?")}]')
    lines.append(f'*{c.get("company",c["symbol"])} | {c.get("ai_category","")} | Pricing: {c.get("pricing_power","?")} | Smart Money: {c.get("smart_money_13f","?")} | Rotation: {c.get("sector_rotation_impact","?")}*')
    lines.append('')
    lines.append(c.get('analyst_note',''))
    lines.append('')
    lines.append(f'**Catalysts:** {c.get("key_catalysts","")}')
    lines.append(f'**Risks:** {c.get("key_risks","")}')
    lines.append(f'**Buy Zone:** {c.get("buy_zone","—")}  |  **Target:** {c.get("price_target","—")}  |  **Stop:** {c.get("stop_loss","—")}')
    lines.append(f'**Hold while:** {hold}')
    lines.append(f'**Exit if:** {xit}')
    lines.append('')

lines += [
    '---', '',
    '## All Candidates',
    '',
    '| Rank | Symbol | Score | Conv | Rotation | Pricing Power | Buy Zone | Target | Stop | Earnings |',
    '|------|--------|-------|------|----------|---------------|----------|--------|------|----------|',
]
for c in all_candidates:
    rot_emoji = '✅' if c.get('sector_rotation_impact')=='FAVORED' else '❌' if c.get('sector_rotation_impact')=='DISFAVORED' else '➖'
    lines.append(
        f'| #{c["rank"]} | **{c["symbol"]}** | {c.get("final_score",0):.1f} | {c.get("conviction","?")} | {rot_emoji} {c.get("sector_rotation_impact","?")} | {c.get("pricing_power","?")} | {c.get("buy_zone","—")} | {c.get("price_target","—")} | {c.get("stop_loss","—")} | {c.get("earnings_date","—")} ({c.get("earnings_days_away","?")}d) |'
    )

lines += [
    '', '---', '',
    '## Sector Rotation & Smart Money Detail',
    '',
    f'**Rotation thesis:** {rotation_summary.get("rotation_rationale","")}',
    '',
    '**Smart Money Accumulating:**',
]
for c in all_candidates:
    if c.get('smart_money_13f') == 'SMART_MONEY_ACCUMULATING':
        lines.append(f'- **{c["symbol"]}**: {c.get("smart_money_detail","")}')

lines += ['', '**Pricing Power Leaders:**']
for c in all_candidates:
    if c.get('pricing_power') in ('PRICING_LEADER',):
        lines.append(f'- **{c["symbol"]}** ({c.get("company","")}): {c.get("pricing_power_detail","")[:120]}...')

lines += ['', '**Insider Activity Flags:**']
for c in all_candidates:
    if c.get('insider_activity') in ('BULLISH','BULLISH_INSIDER','BEARISH','BEARISH_INSIDER'):
        flag = '🟢' if 'BULLISH' in c.get('insider_activity','') else '🔴'
        lines.append(f'- {flag} **{c["symbol"]}** [{c.get("insider_activity","")}]: {c.get("insider_detail","")}')

lines += ['', '---', '', '## Taiwan Ecosystem Signals', '']
for sig in macro_summary.get('taiwan_signals', []):
    lines.append(f'- {sig}')

lines += ['', '---', '', '## Emerging Tech Intelligence', '']
for t in macro_summary.get('emerging_tech_themes', []):
    lines.append(f'- {t}')

lines += ['', '---', '', '## Government Catalyst Tracker', '',
          '| Company | Type | Amount | Status | Priced In | Key Upside | Key Risk |',
          '|---------|------|--------|--------|-----------|------------|----------|']
for g in macro_summary.get('govt_catalysts', []):
    lines.append(f'| {g["company"]} | {g["type"]} | {g["amount"]} | {g["status"]} | {g["priced_in"]} | {g["upside"][:60]}... | {g["risk"][:60]}... |')

lines.append('')
content = '\n'.join(lines) + '\n'

with open('/home/user/scan_log.md', 'w', encoding='utf-8') as f:
    f.write(content)
print('scan_log.md written')
print(f'scan_log.md size: {len(content)} chars')
